backend:
  name: test-repo
  branch: main
  repo: GoNation/thc
media_folder: public/img
public_folder: img
collections:
  - name: 'sidebysideimage'
    label: 'Side By Side Image Variants'
    folder: 'content/sidebysideimage'
    create: true
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'sidebysideimage',
        }
      - {
          label: 'Side By Side Image Container Style',
          name: 'sideBySideImageContainerStyle',
          widget: 'string',
        }
      - {
          label: 'Is Reversed',
          name: 'isReversed',
          widget: 'boolean',
          default: false,
        } # Added this line for the boolean value
      - label: 'CTA Configuration'
        name: 'ctaConfig'
        widget: 'object'
        fields:
          - { label: 'Base Style', name: 'baseStyle', widget: 'string' }
          - {
              label: 'Primary Filled Style',
              name: 'primaryFilledStyle',
              widget: 'string',
            }
          - { label: 'Tertiary Style', name: 'tertiaryStyle', widget: 'string' }
          - { label: 'Default Style', name: 'defaultStyle', widget: 'string' }
      - label: 'Content Component Reference'
        name: 'contentComponentReference'
        widget: 'relation'
        collection: 'content_component'
        searchFields: ['title', 'subtitle']
        valueField: 'title'
        displayFields: ['title']
        create: false
      - label: 'Image Configuration'
        name: 'imageConfig'
        widget: 'object'
        fields:
          - {
              label: 'Container Style',
              name: 'containerStyle',
              widget: 'string',
            }
          - {
              label: 'Relative Container Style',
              name: 'relativeContainerStyle',
              widget: 'string',
            }
          - { label: 'Image Style', name: 'imageStyle', widget: 'string' }
  - name: 'config'
    label: 'Website Configuration'
    files:
      - label: 'Settings'
        name: 'settings'
        file: 'config.md' # Update this with the actual path to your settings file
        fields:
          - { label: 'Business ID', name: 'id', widget: 'string' }
          - { label: 'Domain', name: 'domain', widget: 'string' }
          - {
              label: 'Hard Coded Address Text',
              name: 'hardCodedAddressText',
              widget: 'string',
            }
          - {
              label: 'Hard Coded Address URL',
              name: 'hardCodedAddressURL',
              widget: 'string',
            }

          # Colors Configuration
          - label: 'Colors'
            name: 'COLORS'
            widget: 'object'
            fields:
              - { label: 'Primary', name: 'primary', widget: 'string' }
              - { label: 'Secondary', name: 'secondary', widget: 'string' }
              # ... (add other color fields similarly)
              - { label: 'Tertiary', name: 'tertiary', widget: 'string' }
              - { label: 'Dark', name: 'dark', widget: 'string' }
              - { label: 'Background', name: 'background', widget: 'string' }
              - { label: 'Light', name: 'light', widget: 'string' }

          # IFrame Settings Configuration
          - label: 'IFrame Settings'
            name: 'IFRAME_SETTINGS'
            widget: 'object'
            fields:
              - { label: 'URL', name: 'url', widget: 'string' }
              - { label: 'Embed', name: 'embed', widget: 'text' }

          # Routes Configuration
          - label: 'Routes'
            name: 'ROUTES'
            widget: 'list'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - {
                  label: 'Path',
                  name: 'path',
                  widget: 'string',
                  required: false,
                }
              - { label: 'URL', name: 'url', widget: 'string', required: false }
              - {
                  label: 'Page Description',
                  name: 'pageDescription',
                  widget: 'text',
                  required: false,
                }
              # ... (continue in similar fashion for the other route attributes)
              - label: 'Children'
                name: 'children'
                widget: 'list'
                required: false
                fields:
                  - { label: 'Name', name: 'name', widget: 'string' }
                  # ... (continue in similar fashion for the children attributes)

          # Filtered Gallery Images Configuration
          - label: 'Filtered Gallery Images'
            name: 'FILTERED_GALLERY_IMAGES'
            widget: 'list'
            fields:
              - { label: 'Image', name: 'image', widget: 'string' }
